global:
  scrape_interval: 15s  # Intervalo de coleta

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']
